/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicalRecords;

/**
 *
 * @author Bim
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoPNG = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        patient = new javax.swing.JPanel();
        PatientPNG = new javax.swing.JLabel();
        Patients = new javax.swing.JLabel();
        Reports = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Medicines = new javax.swing.JPanel();
        PatientPNG1 = new javax.swing.JLabel();
        Patients1 = new javax.swing.JLabel();
        Earnings = new javax.swing.JPanel();
        PatientPNG2 = new javax.swing.JLabel();
        Patients2 = new javax.swing.JLabel();
        Checkups = new javax.swing.JPanel();
        PatientPNG3 = new javax.swing.JLabel();
        Patients3 = new javax.swing.JLabel();
        Vaccine = new javax.swing.JPanel();
        PatientPNG4 = new javax.swing.JLabel();
        Patients4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        LogoPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/Home Page (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(595, 595, 595)
                .addComponent(LogoPNG, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoPNG, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patient.setBackground(new java.awt.Color(255, 255, 255));
        patient.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 5, true));
        patient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patientMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                patientMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                patientMouseExited(evt);
            }
        });

        PatientPNG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/icon-patients.png"))); // NOI18N

        Patients.setBackground(new java.awt.Color(0, 0, 0));
        Patients.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Patients.setForeground(new java.awt.Color(0, 0, 0));
        Patients.setText("Patients");

        javax.swing.GroupLayout patientLayout = new javax.swing.GroupLayout(patient);
        patient.setLayout(patientLayout);
        patientLayout.setHorizontalGroup(
            patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Patients, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientPNG))
                .addGap(30, 30, 30))
        );
        patientLayout.setVerticalGroup(
            patientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, patientLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(PatientPNG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patients)
                .addGap(16, 16, 16))
        );

        jPanel2.add(patient, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 19, 154, -1));

        Reports.setBackground(new java.awt.Color(255, 255, 255));
        Reports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 5, true));
        Reports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReportsMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/icon-treatment.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reports");

        javax.swing.GroupLayout ReportsLayout = new javax.swing.GroupLayout(Reports);
        Reports.setLayout(ReportsLayout);
        ReportsLayout.setHorizontalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReportsLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(ReportsLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)))
                .addGap(31, 31, 31))
        );
        ReportsLayout.setVerticalGroup(
            ReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReportsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(Reports, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 19, -1, 157));

        Medicines.setBackground(new java.awt.Color(255, 255, 255));
        Medicines.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 5, true));
        Medicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicinesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MedicinesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MedicinesMouseExited(evt);
            }
        });

        PatientPNG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/icon-medicines.png"))); // NOI18N

        Patients1.setBackground(new java.awt.Color(0, 0, 0));
        Patients1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Patients1.setForeground(new java.awt.Color(0, 0, 0));
        Patients1.setText("Medicines");

        javax.swing.GroupLayout MedicinesLayout = new javax.swing.GroupLayout(Medicines);
        Medicines.setLayout(MedicinesLayout);
        MedicinesLayout.setHorizontalGroup(
            MedicinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicinesLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(MedicinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Patients1)
                    .addComponent(PatientPNG1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MedicinesLayout.setVerticalGroup(
            MedicinesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MedicinesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PatientPNG1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patients1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.add(Medicines, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 237, 154, -1));

        Earnings.setBackground(new java.awt.Color(255, 255, 255));
        Earnings.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 5, true));
        Earnings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EarningsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EarningsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EarningsMouseExited(evt);
            }
        });

        PatientPNG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/icon-earning.png"))); // NOI18N
        PatientPNG2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientPNG2MouseClicked(evt);
            }
        });

        Patients2.setBackground(new java.awt.Color(0, 0, 0));
        Patients2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Patients2.setForeground(new java.awt.Color(0, 0, 0));
        Patients2.setText("Earnings");

        javax.swing.GroupLayout EarningsLayout = new javax.swing.GroupLayout(Earnings);
        Earnings.setLayout(EarningsLayout);
        EarningsLayout.setHorizontalGroup(
            EarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EarningsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(EarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Patients2)
                    .addComponent(PatientPNG2))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        EarningsLayout.setVerticalGroup(
            EarningsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EarningsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(PatientPNG2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patients2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(Earnings, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 237, -1, 157));

        Checkups.setBackground(new java.awt.Color(255, 255, 255));
        Checkups.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 5, true));
        Checkups.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CheckupsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CheckupsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CheckupsMouseExited(evt);
            }
        });

        PatientPNG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/icon-doctors-stethoscope.png"))); // NOI18N

        Patients3.setBackground(new java.awt.Color(0, 0, 0));
        Patients3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Patients3.setForeground(new java.awt.Color(0, 0, 0));
        Patients3.setText("Checkups");

        javax.swing.GroupLayout CheckupsLayout = new javax.swing.GroupLayout(Checkups);
        Checkups.setLayout(CheckupsLayout);
        CheckupsLayout.setHorizontalGroup(
            CheckupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckupsLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(CheckupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Patients3)
                    .addComponent(PatientPNG3))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        CheckupsLayout.setVerticalGroup(
            CheckupsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CheckupsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PatientPNG3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patients3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel2.add(Checkups, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 462, -1, -1));

        Vaccine.setBackground(new java.awt.Color(255, 255, 255));
        Vaccine.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 255, 255), 5, true));
        Vaccine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VaccineMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VaccineMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VaccineMouseExited(evt);
            }
        });

        PatientPNG4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/icon-vaccine.png"))); // NOI18N

        Patients4.setBackground(new java.awt.Color(0, 0, 0));
        Patients4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Patients4.setForeground(new java.awt.Color(0, 0, 0));
        Patients4.setText("Vaccine");

        javax.swing.GroupLayout VaccineLayout = new javax.swing.GroupLayout(Vaccine);
        Vaccine.setLayout(VaccineLayout);
        VaccineLayout.setHorizontalGroup(
            VaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VaccineLayout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(VaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VaccineLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Patients4))
                    .addComponent(PatientPNG4))
                .addGap(28, 28, 28))
        );
        VaccineLayout.setVerticalGroup(
            VaccineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VaccineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PatientPNG4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Patients4)
                .addGap(21, 21, 21))
        );

        jPanel2.add(Vaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 462, -1, 157));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1479, 109, 41, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/Large.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 877, 613));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 600, 119, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1650, 1080));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void patientMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseEntered
        // TODO add your handling code here:
        patient.setBackground(java.awt.Color.decode("#deedee"));
    }//GEN-LAST:event_patientMouseEntered

    private void ReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseEntered
        // TODO add your handling code here:
        Reports.setBackground(java.awt.Color.decode("#deedee"));
    }//GEN-LAST:event_ReportsMouseEntered

    private void MedicinesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicinesMouseEntered
        // TODO add your handling code here:
        Medicines.setBackground(java.awt.Color.decode("#deedee"));
    }//GEN-LAST:event_MedicinesMouseEntered

    private void EarningsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EarningsMouseEntered
        // TODO add your handling code here:
        Earnings.setBackground(java.awt.Color.decode("#deedee"));
    }//GEN-LAST:event_EarningsMouseEntered

    private void CheckupsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckupsMouseEntered
        // TODO add your handling code here:
        Checkups.setBackground(java.awt.Color.decode("#deedee"));
    }//GEN-LAST:event_CheckupsMouseEntered

    private void VaccineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VaccineMouseEntered
        // TODO add your handling code here:
        Vaccine.setBackground(java.awt.Color.decode("#deedee"));
    }//GEN-LAST:event_VaccineMouseEntered

    private void patientMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseExited
        // TODO add your handling code here:
        patient.setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_patientMouseExited

    private void ReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseExited
        // TODO add your handling code here:
        Reports.setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_ReportsMouseExited

    private void MedicinesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicinesMouseExited
        // TODO add your handling code here:
        Medicines.setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_MedicinesMouseExited

    private void EarningsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EarningsMouseExited
        // TODO add your handling code here:
        Earnings.setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_EarningsMouseExited

    private void CheckupsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckupsMouseExited
        // TODO add your handling code here:
        Checkups.setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_CheckupsMouseExited

    private void VaccineMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VaccineMouseExited
        // TODO add your handling code here:
        Vaccine.setBackground(java.awt.Color.WHITE);
    }//GEN-LAST:event_VaccineMouseExited

    private void patientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientMouseClicked
        // TODO add your handling code here:
        PatientGUI patients = new PatientGUI();
        this.setVisible(false);
        patients.setVisible(true);
    }//GEN-LAST:event_patientMouseClicked

    private void MedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicinesMouseClicked
        // TODO add your handling code here:
        MedicineGUI medicine = new MedicineGUI();
        this.setVisible(false);
        medicine.setVisible(true);
    }//GEN-LAST:event_MedicinesMouseClicked

    private void CheckupsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckupsMouseClicked
        // TODO add your handling code here:
        Checkup checkup = new Checkup();
        this.setVisible(false);
        checkup.setVisible(true);
    }//GEN-LAST:event_CheckupsMouseClicked

    private void ReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsMouseClicked
        // TODO add your handling code here:
        Reports rep = new Reports();
        this.setVisible(false);
        rep.setVisible(true);
    }//GEN-LAST:event_ReportsMouseClicked

    private void EarningsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EarningsMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new Earnings().setVisible(true);
    }//GEN-LAST:event_EarningsMouseClicked

    private void PatientPNG2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientPNG2MouseClicked
        // TODO add your handling 
    }//GEN-LAST:event_PatientPNG2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LogIn().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void VaccineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VaccineMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new VaccineGUI().setVisible(true);
    }//GEN-LAST:event_VaccineMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Checkups;
    private javax.swing.JPanel Earnings;
    private javax.swing.JLabel LogoPNG;
    private javax.swing.JPanel Medicines;
    private javax.swing.JLabel PatientPNG;
    private javax.swing.JLabel PatientPNG1;
    private javax.swing.JLabel PatientPNG2;
    private javax.swing.JLabel PatientPNG3;
    private javax.swing.JLabel PatientPNG4;
    private javax.swing.JLabel Patients;
    private javax.swing.JLabel Patients1;
    private javax.swing.JLabel Patients2;
    private javax.swing.JLabel Patients3;
    private javax.swing.JLabel Patients4;
    private javax.swing.JPanel Reports;
    private javax.swing.JPanel Vaccine;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel patient;
    // End of variables declaration//GEN-END:variables
}
