/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicalRecords;

import java.io.File;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Bim
 */
public class Reports extends javax.swing.JFrame {

    ArrayList<Patient> allPatients = new ArrayList<>();
    ArrayList<BillingInfo> allRecord = new ArrayList<>();
    ArrayList<Medicine> allMedicines = new ArrayList<>();

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
        readAllMData();
        readAllPData();
        readAllRData();
    }

    void readAllMData() {
        try {
            File pfile = new File("mdata.txt");
            Scanner scan = new Scanner(pfile);

            while (scan.hasNextLine()) {
                String data = scan.nextLine();
                String[] curData = data.split(";");
                Medicine medicine = new Medicine();

                medicine.setId(Integer.parseInt(curData[0]));

                medicine.setName(curData[1]);

                medicine.setSellingPrice(Integer.parseInt(curData[2]));

                medicine.setBuyingPrice(Integer.parseInt(curData[3]));

                medicine.setQuantity(Integer.parseInt(curData[4]));

                medicine.setDescription(curData[5]);

                allMedicines.add(medicine);

            }

            scan.close();

        } catch (Exception e) {

        }
    }

    void readAllPData() {
        try {
            File pfile = new File("pdata.txt");
            Scanner scan = new Scanner(pfile);

            while (scan.hasNextLine()) {
                String data = scan.nextLine();
                String[] curData = data.split(";");
                Patient patient = new Patient();
                patient.setId(Integer.parseInt(curData[0]));

                patient.setName(curData[1]);

                patient.setAge(Integer.parseInt(curData[2]));

                patient.setGender(curData[3]);

                patient.setAddress(curData[4]);

                patient.setContact(curData[5]);

                allPatients.add(patient);

            }

            scan.close();

        } catch (Exception e) {

        }
    }

    void readAllRData() {
        try {
            File pfile = new File("record.txt");
            Scanner scan = new Scanner(pfile);

            while (scan.hasNextLine()) {
                String data = scan.nextLine();
                String[] curData = data.split(";");
                BillingInfo record = new BillingInfo();
                record.setPatientID(Integer.parseInt(curData[0]));

                record.setFee(Integer.parseInt(curData[1]));

                record.setRecomendation(curData[2]);

                record.setDate(curData[3]);
                String[] mList = curData[4].split(",");

                for (int i = 0; i < mList.length; i++) {
                    record.setMedicineID(Integer.parseInt(mList[i]));

                }
                allRecord.add(record);
            }

            scan.close();

        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        rec = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pr = new javax.swing.JTextArea();
        saveAsPDF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Report Menu");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Luchimir Hospital");

        home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(0, 0, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(596, 596, 596)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home)
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(717, 717, 717)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        rec.setBackground(new java.awt.Color(153, 153, 153));
        rec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rec.setForeground(new java.awt.Color(0, 153, 0));
        rec.setText("Get Record");
        rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID to search:");

        pr.setBackground(new java.awt.Color(204, 255, 204));
        pr.setColumns(20);
        pr.setRows(5);
        jScrollPane1.setViewportView(pr);

        saveAsPDF.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveAsPDF.setForeground(new java.awt.Color(0, 0, 0));
        saveAsPDF.setText("Save as PDF");
        saveAsPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsPDFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveAsPDF, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(385, 385, 385)
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(714, 714, 714)
                            .addComponent(rec, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1453, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(rec)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveAsPDF)
                .addGap(0, 275, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1650, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    Patient getPData(int cid) {
        for (int i = 0; i < allPatients.size(); i++) {
            if (allPatients.get(i).getId() == cid) {
                return allPatients.get(i);
            }
        }
        return null;
    }

    Medicine getMData(int cid) {
        for (int i = 0; i < allMedicines.size(); i++) {
            if (allMedicines.get(i).getId() == cid) {
                return allMedicines.get(i);
            }
        }
        return null;
    }


    private void recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recActionPerformed
        // TODO add your handling code here:
        if (id.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Id field is empty!");
        } else {
            for (int i = 0; i < allRecord.size(); i++) { //kuhag ID sa patient ug name
                if (allRecord.get(i).getPatientID() == Integer.parseInt(id.getText())) {
                    pr.append("\n\nPatient Info\n\n");
                    Patient patient = getPData(allRecord.get(i).getPatientID());

                    pr.append("Patient Name: " + patient.getName() + "\n");
                    pr.append("Patient Contact: " + patient.getContact() + "\n");
                    pr.append("\nAll Recomended Medicines\n");

                    ArrayList<Integer> tmp = allRecord.get(i).getMedicineID();
                    for (int j = 0; j < tmp.size(); j++) {
                        Medicine medicine = getMData(tmp.get(j));
                        pr.append(medicine.getName() + "\n");
                    }

                    pr.append("\nDate " + allRecord.get(i).getDate());
                    pr.append("\nRecomendation:\n" + allRecord.get(i).getRecomendation());
                    pr.append("\n*********************************************************************************\n");
                }
            }
        }
    }//GEN-LAST:event_recActionPerformed

    private void saveAsPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsPDFActionPerformed
        // TODO add your handling code here:
        if (pr.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No data to print!");
        } else {
            try {
                pr.print();
            } catch (java.awt.print.PrinterException e) {
                System.err.format("No printer found", e.getMessage());
            }
        }
    }//GEN-LAST:event_saveAsPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pr;
    private javax.swing.JButton rec;
    private javax.swing.JButton saveAsPDF;
    // End of variables declaration//GEN-END:variables
}
