/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MedicalRecords;

import java.io.File;
import java.io.FileWriter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Bim
 */
public class VaccineGUI extends javax.swing.JFrame {

    ArrayList<Patient> allPatients = new ArrayList<>();
    ArrayList<vaccineRecord> allRecord = new ArrayList<>();

    /**
     * Creates new form VaccineGUI
     */
    public VaccineGUI() {
        initComponents();
        readAllPData();
        readAllVData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nob = new javax.swing.JTextField();
        pid = new javax.swing.JTextField();
        vn = new javax.swing.JTextField();
        nod = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        save = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vax = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1636, 136));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Vaccine Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Luchimir Hospital");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(751, 82, -1, -1));

        home.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        home.setForeground(new java.awt.Color(0, 0, 255));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 0, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1650, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Patient ID");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Vaccine Name");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Number of Doses");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Number of Boosters");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        nob.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nob.setForeground(new java.awt.Color(0, 0, 0));
        nob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobActionPerformed(evt);
            }
        });
        jPanel3.add(nob, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 460, -1));

        pid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pid.setForeground(new java.awt.Color(0, 0, 0));
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        jPanel3.add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 460, -1));

        vn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        vn.setForeground(new java.awt.Color(0, 0, 0));
        vn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vnActionPerformed(evt);
            }
        });
        jPanel3.add(vn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 460, -1));

        nod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nod.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.add(nod, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 460, -1));

        search.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        search.setForeground(new java.awt.Color(204, 0, 0));
        search.setText("Search");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel3.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 550, 150, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MedicalRecords/images/Vaccine.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("COVID-19 Vaccine");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        save.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        save.setForeground(new java.awt.Color(51, 204, 0));
        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 550, 150, 50));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 650));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        vax.setBackground(new java.awt.Color(255, 255, 255));
        vax.setColumns(20);
        vax.setForeground(new java.awt.Color(0, 0, 0));
        vax.setRows(5);
        jScrollPane1.setViewportView(vax);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 850, 650));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1650, 940));

        setBounds(0, 0, 1650, 1080);
    }// </editor-fold>//GEN-END:initComponents

    private void nobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nobActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    Patient getPData(int cid) {
        for (int i = 0; i < allPatients.size(); i++) {
            if (allPatients.get(i).getId() == cid) {
                return allPatients.get(i);
            }
        }
        return null;
    }

    vaccineRecord getRData(int cid) {
        for (int i = 0; i < allRecord.size(); i++) {
            if (allRecord.get(i).getPatientID() == cid) {
                return allRecord.get(i);
            }
        }
        return null;
    }

    void readAllVData() {
        try {
            File pfile = new File("vdata.txt");
            Scanner scan = new Scanner(pfile);

            while (scan.hasNextLine()) {
                String data = scan.nextLine();
                String[] curData = data.split(";");
                vaccineRecord record = new vaccineRecord();
                record.setPatientID(Integer.parseInt(curData[0]));

                record.setvName(curData[1]);

                record.setNumDoses(Integer.parseInt(curData[2]));
                record.setNumBoosters(Integer.parseInt(curData[3]));

                allRecord.add(record);
            }

            scan.close();

        } catch (Exception e) {

        }
    }

    void readAllPData() {
        try {
            File pfile = new File("pdata.txt");
            Scanner scan = new Scanner(pfile);

            while (scan.hasNextLine()) {
                String data = scan.nextLine();
                String[] curData = data.split(";");
                Patient patient = new Patient();
                patient.setId(Integer.parseInt(curData[0]));

                patient.setName(curData[1]);

                patient.setAge(Integer.parseInt(curData[2]));

                patient.setGender(curData[3]);

                patient.setAddress(curData[4]);

                patient.setContact(curData[5]);

                allPatients.add(patient);

            }

            scan.close();

        } catch (Exception e) {

        }
    }

    boolean PatientIdExist() {

        for (int i = 0; i < allPatients.size(); i++) {
            if (pid.getText().equals(allPatients.get(i).getId() + "")) {
                return false;
            }
        }

        return true;
    }

    void SaveAllVData() {
        try {
            FileWriter fileWriter = new FileWriter("vdata.txt");

            for (int i = 0; i < allRecord.size(); i++) {
                fileWriter.append(allRecord.get(i).getPatientID() + ";" + allRecord.get(i).getvName() + ";" + allRecord.get(i).getNumDoses() + ";" + allRecord.get(i).getNumBoosters() + ";");
                int tmp = allRecord.get(i).getPatientID();
                fileWriter.append(tmp + ",");

                fileWriter.append("\n");
            }

            fileWriter.close();
        } catch (Exception e) {

        }
    }

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pidActionPerformed


    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        if (pid.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Id field is empty!");
        } else {
            for (int i = 0; i < allRecord.size(); i++) {
                if (allRecord.get(i).getPatientID() == Integer.parseInt(pid.getText())) {
                    vax.append("\n\nPatient Info\n\n");
                    Patient patient = getPData(allRecord.get(i).getPatientID());
                    vaccineRecord vrec = getRData(allRecord.get(i).getPatientID());

                    vax.append("Patient Name: " + patient.getName() + "\n");
                    vax.append("Vaccine Name: " + vrec.getvName() + "\n");
                    vax.append("Number of Doses: " + vrec.getNumDoses() + "\n");
                    vax.append("Number of Boosters: " + vrec.getNumBoosters() + "\n");

                    vax.append("\n********************************************************************************************************************************************\n");
                }
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void vnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vnActionPerformed

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if (pid.getText().equals("") || vn.getText().equals("") || nod.getText().equals("") || nob.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
        } else if (PatientIdExist()) {
            JOptionPane.showMessageDialog(null, "Patient Id didn't Exist!");
        } else {

            try {

                vaccineRecord vacInfo = new vaccineRecord();

                vacInfo.setPatientID(Integer.parseInt(pid.getText()));
                vacInfo.setvName(vn.getText());
                vacInfo.setNumDoses(Integer.parseInt(nod.getText()));
                vacInfo.setNumBoosters(Integer.parseInt(nob.getText()));
                allRecord.add(vacInfo);

                SaveAllVData();
                pid.setText("");
                vn.setText("");
                nod.setText("");
                nob.setText("");
            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaccineGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VaccineGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nob;
    private javax.swing.JTextField nod;
    private javax.swing.JTextField pid;
    private javax.swing.JButton save;
    private javax.swing.JButton search;
    private javax.swing.JTextArea vax;
    private javax.swing.JTextField vn;
    // End of variables declaration//GEN-END:variables
}
